# Service to take a point cloud and segmentation mask, output object geometry (2D) and object center coordinate (2D)
sensor_msgs/PointCloud2 cloud
sensor_msgs/Image mask
---
geometry_msgs/Polygon geometry
geometry_msgs/Point center
